#!/usr/bin/python

class Problem2:
	'''
	Even Fibonacci numbers
	Problem 2
	4613732

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	'''

	def solution(self):
		x,y = 1, 1
		summ = 0
		while y <= 4000000:
			if not y % 2:
				summ += y

			x,y = y, x + y

		return summ

problem = Problem2()
print problem.solution()